global:
  scrape_interval: 15s  # как часто собирать метрики

scrape_configs:
  - job_name: 'spring-services'
    static_configs:
      - targets:
          - 'api-gateway:8080'
          - 'order-service:8081'
          - 'payment-service:8082'
          - 'inventory-service:8084'
          - 'user-service:8085'
          - 'analytics-service:8086'
          - 'notification-service:8087'
